apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
spec:
  type: NodePort
  selector:
    app: chat-backend
  ports:
  - port: 88
    targetPort: 88
    nodePort: 30088
    protocol: TCP
