apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: tanase0/backend-chat-std:latest
        ports:
        - containerPort: 88
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/chatdb
